### ISSUE TITLE
Syntax highlighting issue on comments

### ISSUE THREAD

**Issue by pchaigno** [textmate/java.tmbundle#33] opened 2015-02-14 12:49 UTC
A `<` character in comments seems to break the syntax highlighting for the code following it.
(It can be seen directly on GitHub code samples because this grammar is used by GitHub to highlight Java code.)

```java
/**
 * Height of the returned pictures (resized by keeping aspect ratio) (api parameter thumbHeight)
 *
 * If negative (thumbHeight<0) the parameter is ignored and sybos default is used
 */
public int getThumbHeight() {
    return thumbHeight;
}
```

This was originally reported at github/linguist#2090.

/cc @itshorty

**Comment by sorbits** [comment] 2015-02-14 16:38
This is a duplicate of #32 which has been resolved.

**Closed** 2015-02-14 16:38 UTC
Labels: duplicate

**Comment by pchaigno** [comment] 2015-02-14 16:39
Arf! Sorry, I should have checked before :/
